services:
  mysql:
    image: mysql:8.4
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rga_user
      MYSQL_DATABASE: rga
      MYSQL_USER: rga_user
      MYSQL_PASSWORD: rgapw
    ports:
      - "3306:3306"
    volumes:
      - "C:/mysql-data:/var/lib/mysql"

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - "C:/grafana-data:/var/lib/grafana"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - "${USERPROFILE}/mosquitto.conf:/mosquitto/config/mosquitto.conf"
