services:
  mysql:
    image: mysql:8.4
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rga_user
      MYSQL_DATABASE: rga
      MYSQL_USER: rga_user
      MYSQL_PASSWORD: rgapw
    ports:
      - '3306:3306'
    volumes:
      - 'C:/mysql-data:/var/lib/mysql'

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - '8090:8080'

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    ports:
      - '3000:3000'
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
      GF_AUTH_ANONYMOUS_ORG_ROLE: 'Admin'
      GF_INSTALL_PLUGINS: 'volkovlabs-form-panel'
    volumes:
      - 'C:/grafana-data:/var/lib/grafana'
      - './grafana/grafana.ini:/etc/grafana/grafana.ini'
      - './grafana/provisioning/datasources:/etc/grafana/provisioning/datasources'
      - './grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards'

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - '1883:1883'
    volumes:
      - '${USERPROFILE}/mosquitto.conf:/mosquitto/config/mosquitto.conf'

  mqtt_bridge:
    build:
      context: .
      dockerfile: mqtt_bridge/Dockerfile
    container_name: mqtt_bridge
    depends_on:
      - mosquitto
      - mysql
    ports:
      - '8080:8080'
    environment:
      MQTT_BROKER: 169.254.11.119
      MQTT_PORT: 1883
