apiVersion: 1

datasources:
  - name: 'RGA MySQL'
    type: mysql
    access: proxy
    url: 'mysql:3306'
    database: rga
    user: rga_user
    secureJsonData:
      password: rgapw
    isDefault: true
